### ISSUE TITLE
[AN] Configure Authority Node

### ISSUE THREAD

**Issue by dakingha69** [cp-ss2019/decentralized-energy-trading#10]
## Task Description
Set up a configuration for running an authority node which uses the `ValidatorSet` contract of issue #8 and `BlockReward` contract (if possible).

## Acceptance Criteria
- [x] When node is deployed a new account is created
- [x] Exposed `JSON RPC` to interact with
- [ ] Documentation on how to run node
- [ ] Native and `docker` deployments
- [ ] Uses `ValidatorSet` contract
- [ ] (tbd) `BlockReward` contract
- [ ] **Test:** A new account exist in the network
- [ ] **Test:** `JSON RPC` is reachable
- [ ] **Test:** Node should be able to connect to the network
