### ISSUE TITLE
[UC] Implement utility contract

### ISSUE THREAD

**Issue by minhi** [cp-ss2019/decentralized-energy-trading#11]
## Task description

Implement a utility contract that tracks production/consumption of energy of all households. It should be able to settle energy requests by distributing existing energy as fair as possible (netting).

- [x] Track renewable/non-renewable energy production and consumption.
- [x] Set proper rights for energy tracking.
- [x] Tests for renewable/non-renewable energy tracking

- [x] Simple fair settlement algorithm to distribute existing energy.
- [x] Tests for settlement.

**Comment by myronrotter** [comment]
PR #36 implements first FIFS fair settlement algorithm and adds tests.
