### ISSUE TITLE
[HHS] Implement interface to DB

### ISSUE THREAD

**Issue by julia832** [cp-ss2019/decentralized-energy-trading#14]
Implement a write-only interface that allows the Household Server to write the received sensor data to the database.

### Subtasks
- [x] HHS should be able to write data to the database
- [x] HHS should be able to read data from the database
- [x] Add Timestamps in the DB (are already integrated into MongoDB -> Solved)
- [x] Implement getByID

**Comment by dakingha69** [comment]
Closed via #22
