### ISSUE TITLE
[AN] Setup Native Test Network

### ISSUE THREAD

**Issue by paguos** [cp-ss2019/decentralized-energy-trading#30]
## Task Description
Set up a configuration for running an authority node which should be used for the `ValidatorSet` contract (issue #8)

## Acceptance Criteria
- [x] When node is deployed a new account is created
- [x] Exposed `JSON RPC` to interact with
- [x] Documentation on how to run node
- [x] Authority node deployment script
- [x] Bootnode deployment script
- [x] **Test:** A new account exist in the network
- [x] **Test:** `JSON RPC` is reachable
- [x] **Test:** Node should be able to connect to the network
