### ISSUE TITLE
[AN] Write integration tests for docker deployment

### ISSUE THREAD

**Issue by paguos** [cp-ss2019/decentralized-energy-trading#31]
## Task Description
Similar to issue #30 integration test should be written to guarantee the quality of the test network.

## Acceptance Criteria
- [x] **Test:** Only one account for node
- [x] **Test:** `JSON RPC` is reachable
- [x] **Test:** Node should be able to connect to the network

**Comment by dakingha69** [comment]
Closed via https://github.com/cp-ss2019/decentralized-energy-trading/pull/32
