### ISSUE TITLE
[VS] Implement OwnedValidatorSet

### ISSUE THREAD

**Issue by dakingha69** [cp-ss2019/decentralized-energy-trading#8]
## Task Description
In order to have a flexible set of validators for our PoA chain, we need to implement a `ValidatorSet` contract that enables us to add and remove validators. In the scope of an POC and a first version it would make sense to make this contract also ownable. We can basically use this implementation for this https://github.com/parity-contracts/kovan-validator-set/blob/master/contracts/interfaces/BaseOwnedSet.sol.

## Acceptance Criteria
- [x] Owner of contract should be able to add new validator
- [x] Owner of contract should be able to remove misbehaving validators
- [x] Public method to retrieve current validators
- [ ] Basic tests for above functions

**Comment by dakingha69** [comment]
Notes:
- pre-funded account in genesis block should be owner
- modify OwnedValidatorSet such that above account is owner of contract

**Comment by myronrotter** [comment]
@jahandaniyal what is the status on the `ValidatorSet` contract? How can @minhi or myself help you with the `ValidatorSet` contract?
